sudo: required

language: ruby

services:
  - docker

env:
  global:
    - DOCKER_VERSION=1.11.1-0~trusty
    - DOCKER_COMPOSE_VERSION=1.7.1

before_install:
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker version
  - docker-compose version
  - git clone https://github.com/subdee/yii2-nginx-php7-mongo-mariadb-docker.git docker
  - cd docker
  - sed -i s/\\/project// common-compose.yml
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d
  - docker exec php7 /bin/bash -c 'composer install --dev --prefer-dist --no-interaction'
  - docker exec php7 /bin/bash -c './init --env=Development'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/common && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/console && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/backend && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/frontend && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/bin && ./yii migrate --interactive=0'

script:
  - docker exec php7 /bin/bash -c 'cd tests && ../vendor/bin/codecept run'

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 travis.pem
  - ssh-add travis.pem
  - git remote add deploy https://github.com/subdee/myportugal.git
  - git push deploy