sudo: required

language: ruby

services:
  - docker

env:
  global:
    - DOCKER_VERSION=1.11.1-0~trusty
    - DOCKER_COMPOSE_VERSION=1.7.1

before_install:
  - openssl aes-256-cbc -K $encrypted_3e5819d1149d_key -iv $encrypted_3e5819d1149d_iv -in travis.pem.enc -out travis.pem -d
  - git clone https://github.com/subdee/yii2-nginx-php7-mongo-mariadb-docker.git docker
  - gem install sass
  - gem install compass

install:
  - cd docker
  - sed -i s/\\/project// common-compose.yml
  - docker-compose pull
  - docker-compose up -d
  - docker exec php7 /bin/bash -c 'composer install --prefer-dist --no-interaction'
  - cd ../
  - sass frontend/assets/scss/app.scss frontend/web/css/app.css --style compressed
  - sass frontend/assets/scss/theme.scss frontend/web/css/theme.css --style compressed
  - sass frontend/assets/scss/ie.scss frontend/web/css/ie.css --style compressed

before_script:
  - docker exec php7 /bin/bash -c './init --env=Development'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/common && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/console && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/backend && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/frontend && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/bin && ./yii migrate --interactive=0'

script:
  - docker exec php7 /bin/bash -c 'cd tests && ../vendor/bin/codecept run'

after_success:
  - git checkout -b deploy
  - docker exec php7 /bin/bash -c './yii message frontend/config/i18n.php'
  - docker exec php7 /bin/bash -c 'rm -rf tests docker environments .sass-cache'
  - git config user.name "Travis CI"
  - git config user.email "$COMMIT_AUTHOR_EMAIL"
  - git add -A
  - git commit -m "[ci skip] Deployment push"
  - eval "$(ssh-agent -s)"
  - chmod 600 travis.pem
  - ssh-add travis.pem
  - git remote add deploy git@github.com:subdee/myportugal.git
  - git push --force deploy