language: php

php:
  - 7.0

sudo: false

services:
  - mongodb

addons:
  artifacts: true

cache:
  directories:
    - $HOME/.composer/cache

beofre_install:
  - openssl aes-256-cbc -K $encrypted_3e5819d1149d_key -iv $encrypted_3e5819d1149d_iv -in travis.pem.enc -out travis.pem -d

install:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - export PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
  - ./init --env=Development
  - sed -i s/root/travis/ common/config/main-local.php
  - cd tests/codeception/common && codecept build
  - cd ../console && codecept build
  - cd ../backend && codecept build
  - cd ../frontend && codecept build
  - cd ../../../

before_script:
  - mysql -e 'CREATE DATABASE feriados_test;';
  - cd tests/codeception/bin && php yii migrate --interactive=0 && cd ../../..

script:
  - php -S localhost:8080 > /dev/null 2>&1 &
  - cd tests
  - codecept run

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 travis.pem
  - ssh-add travis.pem
  - git remote add deploy https://github.com/subdee/myportugal.git
  - git push deploy
