sudo: required

language: ruby

services:
  - docker

before_install:
  - git clone https://github.com/subdee/yii2-nginx-php7-mongo-mariadb-docker.git docker
  - cd docker
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d
  - docker exec php7 /bin/bash -c 'composer install --dev --prefer-dist --no-interaction'
  - docker exec php7 /bin/bash -c './init --env=Development'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/common && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/console && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/backend && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/frontend && ../../../vendor/bin/codecept build'
  - docker exec php7 /bin/bash -c 'cd tests/codeception/bin && ./yii migrate --interactive=0'

script:
  - docker exec php7 /bin/bash -c 'cd tests && ../vendor/bin/codecept run'