<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '135+ Hotels' => '',
    'About' => '',
    'About Flight' => '',
    'About Hotel' => '',
    'About MyPortugal.nl' => '',
    'Airline' => '',
    'Authentic Portugal - Pusadas and more' => '',
    'Base fare' => '',
    'Book now' => '',
    'Book {offer}' => '',
    'Booking Details' => '',
    'Booking options' => '',
    'Destinations' => '',
    'Duration : {days}d' => '',
    'Excellent Support' => '',
    'Flight Details' => '',
    'Fly & Drives' => '',
    'Get a tailor made quote now' => '',
    'Give yourself a break and escape!' => '',
    'Hotel Details' => '',
    'Hotel fare' => '',
    'Landing' => '',
    'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
                    Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
                    ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla
                    consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget,
                    arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu
                    pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean
                    vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac,
                    enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra
                    nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel
                    augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus,
                    tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed
                    ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio
                    et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante.
                    Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet
                    nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit
                    cursus nunc,' => '',
    'Low Rates & Savings' => '',
    'Mailing List' => '',
    'MyPortugal.nl Header' => '',
    'Need MyPortugal.nl Help?' => '',
    'Nunc cursus libero pur congue arut nimspnty.' => '',
    'Nunc cursus libero purus ac congue arcu cursus ut sed vitae pulvinar massaidp nequetiam lore
                        elerisque.' => '',
    'Payment information' => '',
    'Policies' => '',
    'Return flight' => '',
    'Safety' => '',
    'Sign up for our mailing list to get latest updates and offers.' => '',
    'Signup form' => '',
    'Site Map' => '',
    'Take off' => '',
    'Taxes & Fees' => '',
    'Taxes and fees' => '',
    'This email address has already been taken.' => '',
    'This offer does not exist' => '',
    'Total Price' => '',
    'Total Time' => '',
    'Travel News' => '',
    'View' => '',
    'We respect your privacy' => '',
    'We would be more than happy to help you. Our team advisor are 24/7 at your service to help you.' => '',
    'Why Book with us?' => '',
    'You don\'t want to miss the nature!' => '',
    'Your Personal Information' => '',
    'per person' => '',
    'total price' => '',
    'your email' => '',
    '{hours}h {minutes}m' => '',
    '{n,plural,=1{# day} other{# days}}' => '',
    '{n,plural,=1{# night} other{# nights}}' => '',
    '{n,plural,=1{1 user rating} other{# user ratings}}' => '',
    '{origin} to {destination}' => '',
];
