<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '# of adults' => '',
    '# of children' => '',
    'Amsterdam Schiphol' => '',
    'Brussels' => '',
    'By continuing, you agree to the {termsAndCondsLink}' => '',
    'Dusseldorf' => '',
    'Eindhoven' => '',
    'Email' => '',
    'Extra remarks regarding your booking' => '',
    'First Name' => '',
    'I want to receive promotional offers in the future' => '',
    'Last Name' => '',
    'Leave' => '',
    'Mobile number' => '',
    'Password' => '',
    'Phone number' => '',
    'Preferred airport' => '',
    'Repeat your password' => '',
    'Return' => '',
    'Search' => '',
    'Terms and Conditions' => '',
    'Verify email' => '',
    'You must agree to the terms and conditions' => '',
];
